// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvzV8w9n9TTAF9eNf9FswqDye9CSBUOg',
    appId: '1:829063496130:web:9a760ec9cd073dfa74165b',
    messagingSenderId: '829063496130',
    projectId: 'fitscan-f8e3b',
    authDomain: 'fitscan-f8e3b.firebaseapp.com',
    storageBucket: 'fitscan-f8e3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9razFRqElg_hKJFd_jkNFGo38lrwnow',
    appId: '1:829063496130:android:76bf2f29142827ce74165b',
    messagingSenderId: '829063496130',
    projectId: 'fitscan-f8e3b',
    storageBucket: 'fitscan-f8e3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLm-gKci-NlRIh40M3MXaiHRTgTsc6soE',
    appId: '1:829063496130:ios:8353999c8988c3c674165b',
    messagingSenderId: '829063496130',
    projectId: 'fitscan-f8e3b',
    storageBucket: 'fitscan-f8e3b.firebasestorage.app',
    iosBundleId: 'com.example.projetFitscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLm-gKci-NlRIh40M3MXaiHRTgTsc6soE',
    appId: '1:829063496130:ios:8353999c8988c3c674165b',
    messagingSenderId: '829063496130',
    projectId: 'fitscan-f8e3b',
    storageBucket: 'fitscan-f8e3b.firebasestorage.app',
    iosBundleId: 'com.example.projetFitscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxvzV8w9n9TTAF9eNf9FswqDye9CSBUOg',
    appId: '1:829063496130:web:1466760110bed82c74165b',
    messagingSenderId: '829063496130',
    projectId: 'fitscan-f8e3b',
    authDomain: 'fitscan-f8e3b.firebaseapp.com',
    storageBucket: 'fitscan-f8e3b.firebasestorage.app',
  );
}
